apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: streaming-poc
build:
  artifacts:
  - image: streaming-poc
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deploy/dummy.yaml
