apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: streaming-poc
build:
  artifacts:
  - image: streaming-poc
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: cert-manager
        repo: https://charts.jetstack.io
        remoteChart: cert-manager
        version: v1.2.0
        namespace: cert-manager
        createNamespace: true
        setValues:
          installCRDs: true
  kustomize:
    paths:
      - https://github.com/vectorizedio/redpanda/src/go/k8s/config/crd?ref=v21.7.6
  kubectl:
    manifests:
    - deploy/dummy.yaml